lerna.json, package-lock.json, package.json, packages/core/package.json, packages/react/package.json
=> build: set up larna

packages/core/package.json, packages/react/package.json
=> fix: package names

package-lock.json
=> build: bootstrap monorepo

package-lock.json, packages/core/package.json, packages/core/tsconfig.json, packages/react/package.json, packages/react/tsconfig.json
=> build: add typescript to packages

packages/core/package.json, packages/core/scripts/build.js, packages/react/package.json, packages/react/scripts/build.js
=> build: set up build scripts

.editorconfig
=> chore: set up `.editorconfig`

.vscode/settings.json
=> chore: configure vscode

packages/core/package.json, packages/core/src/index.ts, packages/core/src/types.ts
=> chore: introduce first types

package.json
=> build: add root build script

.gitignore
=> chore: add `.DS_Store`

packages/core/tsconfig.json, packages/react/tsconfig.json
=> build: change compiler target to ES6

package-lock.json, packages/react/package.json
=> chore(deps): install react

package-lock.json, packages/react/tsconfig.json
=> build: configure typescript for react

packages/react/src/types.ts, packages/react/src/withTranslation.tsx
=> feat: introduce `withTranslation` hoc

packages/react/package.json, packages/react/src/index.ts
=> fix: add exports

packages/core/src/types.ts
=> docs: add tsdoc examples

packages/core/src/index.ts, packages/core/src/types.ts
=> feat: introduce `TranslationFn` type

lerna.json, package-lock.json, package.json
=> build: update lerna to version 6

package-lock.json, package.json, packages/core/jest.config.js, packages/core/package.json, packages/core/tsconfig.json, packages/react/jest.config.js, packages/react/package.json, packages/react/tsconfig.json
=> chore: add and configure jest

catchphrase.code-workspace
=> chore: configure vscode multi-root workspaces

.github/dependabot.yml
=> chore: configure dependabot version updates

.github/workflows/node-js.yml, package.json, packages/core/package.json, packages/react/package.json
=> ci: add github action for testing

package-lock.json, packages/react/jest.config.ts, packages/react/package.json
=> chore: set up testing library

packages/core/src/types.ts
=> feat: overhaul the types

packages/core/src/createTranslation.ts
=> feat: add `createTranslation` function

packages/core/src/createTranslation.test.ts
=> test: add `createTranslation` tests

packages/core/src/createCatchphrase.ts, packages/core/src/types.ts
=> feat: add `createCatchphrase` function

packages/react/src/withTranslation.tsx
=> feat: overhaul `withTranslation` higher order component

packages/core/src/createCatchphrase.test.ts
=> test: add `createCatchphrase` tests

package-lock.json, packages/core/package.json, packages/react/package.json
=> chore(dev-deps): upgrade to typescript v4.9

.vscode/settings.json
=> chore: specify typescript path in workspace

packages/core/src/createCatchphrase.ts, packages/core/src/types.ts
=> feat: use `LanguageCode` generic from `createCatchphrase` instance

package-lock.json, package.json
=> chore(deps-dev): update lerna to version 6.1

README.md, packages/core/README.md, packages/react/README.md
=> docs: add `README.md` to packages

package-lock.json, packages/react/package.json
=> chore(deps-dev): install `@testing-library/jest-dom`

.github/workflows/node-js.yml, packages/react/src/withTranslation.test.tsx
=> test: add tests for `withTranslations`

packages/core/src/createCatchphrase.test.ts, packages/core/src/createCatchphrase.ts, packages/core/src/types.ts, packages/react/src/withTranslation.test.tsx
=> feat: configure `defaultLanguage` through parameter

packages/core/src/createCatchphrase.test.ts, packages/core/src/createTranslation.ts, packages/core/src/types.ts
=> feat: add `getTranslations` function

packages/react/src/withTranslation.test.tsx
=> test: update test to use `getTranslations`

packages/core/package.json, packages/react/package.json
=> chore: specify `files`

packages/core/src/createCatchphrase.test.ts, packages/core/src/createCatchphrase.ts, packages/core/src/createTranslation.ts, packages/core/src/types.ts, packages/react/src/withTranslation.test.tsx
=> feat: introduce the `languageSelector`

package-lock.json, package.json
=> chore(deps-dev): update lerna to version 6.4

packages/core/package.json, packages/react/package.json
=> chore: remove `passWithNoTests` argument

.github/FUNDING.yml
=> chore: add sponsorship

.prettierignore, .prettierrc.json, CODE_OF_CONDUCT.md, examples/react-ts/src/main.tsx, package-lock.json, package.json, packages/core/src/createCatchphrase.test.ts, packages/core/src/createTranslation.ts, packages/core/src/types.ts, packages/react/src/withTranslation.test.tsx, packages/react/src/withTranslation.tsx
=> chore: set up prettier

package-lock.json, packages/core/package.json, packages/react/package.json
=> chore(deps-dev): update dependencies

packages/core/package.json, packages/react/package.json
=> chore: add description and keywords

packages/core/package.json, packages/react/package.json
=> ci: reset package versions

lerna.json
=> ci: configure lerna for releasing

lerna.json
=> ci: remove createRelease from config

packages/core/package.json, packages/react/package.json
=> ci: set initial package versions

lerna.json
=> ci: add removed lerna configs again

.npmrc
=> ci: add `.npmrc` file

packages/core/package.json, packages/react/package.json
=> chore: specify `homepage` in packages

packages/core/package.json, packages/react/package.json
=> chore: specify `repository` in packages

.github/workflows/node-js.yml, lerna.json
=> ci: remove `lerna bootstrap` step

packages/core/tsconfig.json, packages/react/tsconfig.json
=> chore: remove obsolete `ts-node` configs from `tsconfig.json` files

package-lock.json, package.json
=> build(deps-dev): update lerna to v7

website/src/pages/index.module.css
=> fix: wrap CTA-buttons on smaller screens

website/src/pages/index.module.css
=> fix: remove horizontal padding

.github/dependabot.yml
=> fix: configure dependabot to recognize examples

website/docs/getting-started/installation.mdx
=> docs: remove `@catchphrase/core` instructions

website/package-lock.json, website/package.json
=> build(deps): update docusaurus packages

examples/react-ts/src/components/Greeting/Greeting.catchphrase.tsx, examples/react-ts/src/components/InformationText/InformationText.catchphrase.tsx
Closes #181 Added some missing commas.
=> style: Fixed format issue.

examples/react-ts/src/catchphrase.ts
Closes #183 Added missing french language to catchphrase.ts.
=> feat: Added new language to catchphrase.ts.

packages/core/deno.json, packages/react/deno.json
=> chore: add `deno.json` configs

packages/core/src/index.ts, packages/react/src/index.ts
=> refactor: export types as types

website/src/content/docs/getting-started/installation.mdx
=> docs: update `Installation` page

examples/react-ts/package-lock.json, examples/react-ts/package.json
=> build(deps-dev): update dependencies

packages/core/src/createCatchphrase.ts, packages/core/src/createTranslation.ts, packages/core/src/types.ts
=> docs: add symbol docs
